"""Public evidence contract emitted by the internal Monte Carlo solver."""

from __future__ import annotations


DIRECT_MC_TRANSPORT_ESTIMATOR_SCHEMA_VERSION: str = "direct_mc_transport.v4"
MC_WORKFLOW_REPLICA_SEED_DERIVATION: str = (
    "sha256_base_seed_mixture_e_over_n_replicate_solver.v1"
)
MC_CASE_SEED_DERIVATION: str = "sha256_base_seed_e_over_n.v1"
MC_SEED_DERIVATION_SCHEMA_VERSION: str = (
    MC_WORKFLOW_REPLICA_SEED_DERIVATION + "+" + MC_CASE_SEED_DERIVATION
)
DIRECT_MC_TRANSPORT_OBSERVATION_PLANES: int = 128
DIRECT_MC_TRANSPORT_LAG_PLANES: tuple[int, ...] = (8, 16, 32, 64)
DIRECT_MC_TRANSPORT_CADENCE_TRIAL_PERIODS: int = 16
DIRECT_MC_TRANSPORT_OBSERVATION_END_FRACTION: float = 0.8

MC_EEDF_ESTIMATOR_SCHEMA_VERSION: str = (
    "exact_bin_residence_piecewise_linear_rate_integrals.v2"
)
MC_MAGNETIC_EEDF_ESTIMATOR_SCHEMA_VERSION: str = (
    "boris_endpoint_energy_residence.v1"
)

WEIGHTED_MC_TRANSPORT_ESTIMATOR_SCHEMA_VERSION: str = (
    "direct_mc_weighted_growth_configured_lag.v6"
)
WEIGHTED_MC_TRANSPORT_MIN_BLOCKS: int = 128
WEIGHTED_MC_TRANSPORT_MIN_EFFECTIVE_LINEAGE_COUNT: float = 128.0
WEIGHTED_MC_TRANSPORT_MIN_EFFECTIVE_LINEAGE_FRACTION: float = 0.05

WEIGHTED_MC_TAIL_ESTIMATOR_SCHEMA_VERSION: str = (
    "reaction_kernel_weighted_ensemble_pooled_estimators.v4"
)
FIELD_PARITY_RESPONSE_ESTIMATOR_SCHEMA_VERSION: str = (
    "common_random_number_field_parity_response.v1"
)


__all__ = [
    "DIRECT_MC_TRANSPORT_CADENCE_TRIAL_PERIODS",
    "DIRECT_MC_TRANSPORT_ESTIMATOR_SCHEMA_VERSION",
    "DIRECT_MC_TRANSPORT_LAG_PLANES",
    "DIRECT_MC_TRANSPORT_OBSERVATION_END_FRACTION",
    "DIRECT_MC_TRANSPORT_OBSERVATION_PLANES",
    "FIELD_PARITY_RESPONSE_ESTIMATOR_SCHEMA_VERSION",
    "MC_CASE_SEED_DERIVATION",
    "MC_EEDF_ESTIMATOR_SCHEMA_VERSION",
    "MC_MAGNETIC_EEDF_ESTIMATOR_SCHEMA_VERSION",
    "MC_SEED_DERIVATION_SCHEMA_VERSION",
    "MC_WORKFLOW_REPLICA_SEED_DERIVATION",
    "WEIGHTED_MC_TAIL_ESTIMATOR_SCHEMA_VERSION",
    "WEIGHTED_MC_TRANSPORT_ESTIMATOR_SCHEMA_VERSION",
    "WEIGHTED_MC_TRANSPORT_MIN_BLOCKS",
    "WEIGHTED_MC_TRANSPORT_MIN_EFFECTIVE_LINEAGE_COUNT",
    "WEIGHTED_MC_TRANSPORT_MIN_EFFECTIVE_LINEAGE_FRACTION",
]
